# Run tests against developer push

# Runs jobs on linux and windows to maintain compatibility.
# The main repo is checked out into a sub-directory because an optional
# second repo may be checked out for testing.

name: cleanup

on:
  push:
    # branches: [ wftest ]
    # branches-ignore: [ master, main ]

jobs:
  build-test:
    name: Node v${{ matrix.node-version }} on ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]
        #os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    # job level env vars used for a couple of steps
    env:
      # see github-glue.test.ts for info on setting these
      GGG_TOKEN: ${{ secrets.GGG_TOKEN }}
      GGG_REPOSITORY: ${{ secrets.GGG_REPOSITORY }}

    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '${{ matrix.node-version }}' # optional, default is 10.x

    - name: Clean up branches and PRs
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GGG_TOKEN}}
        # github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const query = `query($owner:String!, $name:String!) {
            repository(owner:$owner, name:$name){
              pullRequests(last: 3) {
                totalCount,
                nodes {
                  id,
                  title,
                  updatedAt,
                  headRefName
                }
              }
            }
          }`;
          const variables = {
            owner: context.repo.owner,
            name: context.repo.repo
          }
          const result = await github.graphql(query, variables)
          console.log(result.repository.pullRequests.nodes)
      if: env.GGG_TOKEN # || env.GGG_REPOSITORY

    - name: Clean up branches which closes PRs
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GGG_TOKEN}}
        # github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const yesterdayIsh = new Date();
          yesterdayIsh.setUTCHours(-1, 0 ,0);
          const owner = context.repo.owner;
          const name = process.env.GGG_REPOSITORY || context.repo.repo;
          const expireDate = yesterdayIsh.toISOString().replace(/[:.]/g, "_");
          const query = `
            query {
              repository(name: "${name}", owner: "${owner}") {
                  id
                  name
                  refs(refPrefix: "refs/heads/", first: 10) {
                    edges {
                      node {
                        name
                        id
                        pulls:associatedPullRequests(first: 5, states:OPEN) {
                          edges {
                            node {
                              id
                              number
                              title
                            }
                          }
                        }
                      }
                    }
                }
              }
            }
          `;
          console.log(query);
          const result = await github.graphql(query);
          console.log(result);
          console.log(result.repository.refs.edges);
          result.repository.refs.edges.map(br => {
            const name = br.node.name;
            const suffix = name.match(/ggg-test-branch-\s+_(.*)/);
            if (suffix && suffix < expireDate) {
              if (br.node.pulls.edges.length) {
                console.log(`Closing PR ${br.node.pulls.edges[0].node.number}`);
              }
              console.log(`Deleting branch ${br.node.name}`);
            }
          });
      if: env.GGG_TOKEN # || env.GGG_REPOSITORY

    - name: 2Clean up branches and PRs
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GGG_TOKEN}}
        # github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const yesterdayIsh = new Date();
          yesterdayIsh.setUTCHours(-4, 0 ,0);
          const owner = context.repo.owner;
          const name = process.env.GGG_REPOSITORY || context.repo.repo;
          const expireDate = yesterdayIsh.toISOString();
          const query = `{
            search(
              query: "ggg in:title repo:${owner}/${name} is:pr is:open created:<=${expireDate}", type: ISSUE, last: 100) {
              edges {
                node {
                  ... on PullRequest {
                    id
                    number
                    title
                    createdAt
                    updatedAt
                    headRefName
                  }
                }
              }
            }
          }`;
          const result = await github.graphql(query);
          console.log(query);
          console.log(result.search.edges);
          result.search.edges.map(pr => {
              console.log(`Closing PR ${pr.node.number}`);
              console.log(`Deleting branch ${pr.node.headRefName}`);
          });
      if: env.GGG_TOKEN # || env.GGG_REPOSITORY
